In [1]:
import random
from collections import defaultdict

# 1. Create sample survey data (at least 30 responses)
random.seed(42)  # For reproducible random results
n = 30
apps = ['Zomato', 'Swiggy', 'Uber Eats']
payments = ['Paytm', 'PhonePe', 'Credit Card']

data = [
    {
        'Delivery_App': random.choice(apps),
        'Payment_Method': random.choice(payments)
    }
    for _ in range(n)
]

# 2. Build the contingency table manually using nested dictionaries
table = defaultdict(lambda: defaultdict(int))
row_totals = defaultdict(int)
col_totals = defaultdict(int)
grand_total = 0

for row in data:
    app = row['Delivery_App']
    pay = row['Payment_Method']
    table[app][pay] += 1
    row_totals[app] += 1
    col_totals[pay] += 1
    grand_total += 1

# 3. Print the formatted table layout
header_label = "Delivery App \\ Payment"
print(f"{header_label:<24} | " + " | ".join(f"{p:<12}" for p in payments) + " | Total")
print("-" * 75)

for app in apps:
    row_str = f"{app:<24} | "
    for pay in payments:
        count = table[app][pay]
        row_str += f"{count:<12} | "
    row_str += f"{row_totals[app]}"
    print(row_str)

print("-" * 75)
tot_str = f"{'Column Total':<24} | "
for pay in payments:
    tot_str += f"{col_totals[pay]:<12} | "
tot_str += f"{grand_total}"
print(tot_str)

Delivery App \ Payment   | Paytm        | PhonePe      | Credit Card  | Total
---------------------------------------------------------------------------
Zomato                   | 4            | 2            | 5            | 11
Swiggy                   | 5            | 2            | 2            | 9
Uber Eats                | 5            | 2            | 3            | 10
---------------------------------------------------------------------------
Column Total             | 14           | 6            | 10           | 30


In [2]:

import numpy as np
import pandas as pd

# Observed data
# Rows: Spotify, Gaana, YouTube Music
# Columns: Males, Females
observed = np.array([
    [12, 18], # Spotify
    [8, 7],   # Gaana
    [10, 15]  # YouTube Music
])

row_totals = observed.sum(axis=1)
col_totals = observed.sum(axis=0)
grand_total = observed.sum()

print("Row Totals:", row_totals)
print("Column Totals:", col_totals)
print("Grand Total:", grand_total)

expected = np.outer(row_totals, col_totals) / grand_total
print("Expected Counts:\n", expected)

Row Totals: [30 15 25]
Column Totals: [30 40]
Grand Total: 70
Expected Counts:
 [[12.85714286 17.14285714]
 [ 6.42857143  8.57142857]
 [10.71428571 14.28571429]]


In [3]:
import numpy as np
from scipy.stats import chi2_contingency

# 1. Define the observed contingency table from Task 1
# Rows: [Zomato, Swiggy, Uber Eats]
# Columns: [Paytm, PhonePe, Credit Card]
observed = np.array([
    [4, 2, 5],  # Zomato counts
    [5, 2, 2],  # Swiggy counts
    [5, 2, 3]   # Uber Eats counts
])

# 2. Perform the Chi-Square test of independence
chi2_stat, p_value, dof, expected = chi2_contingency(observed)

# 3. Display the results
print(f"Chi-Square Statistic : {chi2_stat:.2f}")
print(f"p-value              : {p_value:.3f}")
print(f"Degrees of Freedom   : {dof}")
print("\nExpected Frequencies:")
print(np.round(expected, 2))

# 4. Conclusion check (alpha = 0.05)
alpha = 0.05
if p_value < alpha:
    print("\nConclusion: Reject the null hypothesis (Significant association exists).")
else:
    print("\nConclusion: Fail to reject the null hypothesis (No significant association).")

Chi-Square Statistic : 1.32
p-value              : 0.858
Degrees of Freedom   : 4

Expected Frequencies:
[[5.13 2.2  3.67]
 [4.2  1.8  3.  ]
 [4.67 2.   3.33]]

Conclusion: Fail to reject the null hypothesis (No significant association).


In [4]:
import numpy as np
from scipy.stats import chisquare

# Observed counts: 18 prefer, 12 do not prefer (Total = 30)
observed = np.array([18, 12])

# Claimed proportion: 70% prefer, 30% do not prefer
total_n = 30
expected_probs = np.array([0.70, 0.30])
expected = expected_probs * total_n

print("Observed:", observed)
print("Expected:", expected)

chi2_stat, p_value = chisquare(f_obs=observed, f_exp=expected)
print("Chi2 Stat:", chi2_stat)
print("p-value:", p_value)

Observed: [18 12]
Expected: [21.  9.]
Chi2 Stat: 1.4285714285714286
p-value: 0.23199772362873072
